[package]

name = "rstracer"
version = "0.0.2"
authors = ["Sondre Lefsaker"]

[profile.dev]
opt-level = 2

[dependencies]
bmp = "0.0.3"

[dependencies.wavefront_obj]
git = "https://github.com/sondrele/wavefront_obj.git"
